# Generated by Django 3.0.6 on 2020-05-13 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chorescheduling', '0004_remove_household_linked_shedule'),
        ('feedstructuring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='chore_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chorescheduling.Chore'),
        ),
    ]
