# Generated by Django 3.0.5 on 2020-05-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorescheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choreschedule',
            name='text',
        ),
        migrations.AddField(
            model_name='choreschedule',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
