# Generated by Django 3.0.6 on 2020-05-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chorescheduling', '0003_auto_20200512_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='linked_shedule',
        ),
    ]
