# Generated by Django 3.0.5 on 2020-05-12 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chorescheduling', '0002_auto_20200505_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChoreInfo',
            fields=[
                ('ciid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('linked_household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chorescheduling.Household')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('num_weeks', models.IntegerField()),
                ('linked_household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chorescheduling.Household')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('week_num', models.IntegerField()),
                ('linked_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chorescheduling.Schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='ChoreSchedule',
        ),
        migrations.AddField(
            model_name='household',
            name='linked_shedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chorescheduling.Schedule'),
        ),
        migrations.AddField(
            model_name='choreinfo',
            name='linked_household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chorescheduling.Household'),
        ),
        migrations.AddField(
            model_name='chore',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chorescheduling.Person'),
        ),
        migrations.AddField(
            model_name='chore',
            name='chore_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chorescheduling.ChoreInfo'),
        ),
        migrations.AddField(
            model_name='chore',
            name='linked_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chorescheduling.Week'),
        ),
    ]
