# Generated by Django 3.0.5 on 2020-05-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chorescheduling', '0003_auto_20200511_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choreinfo',
            name='completed',
        ),
        migrations.AddField(
            model_name='chore',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
