# Generated by Django 3.0.5 on 2020-05-13 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chorescheduling', '0004_auto_20200512_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='linked_shedule',
        ),
    ]
